@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ 
    "make" : "Toyota",
    "model" : "Yaris Cross",
    "year": 2024
    
}

###

@newCar = {{postACar.response.body._id}}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ac602a15f5cc4f3191a2ea9 HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6ab39b6939bb4c3367750d27 HTTP/3.0
content-type: application/json

{ 
    "make" : "Opel"
}

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah