@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ 
    "make" : "Volkswagen",
    "model" : "Beetle"
}

###

@newCar = {{postACar.response.body._id}}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ab39d413359ed55599cfe17 HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6ab39b6939bb4c3367750d27 HTTP/3.0
content-type: application/json

{ 
    "make" : "Opel",
    "model" : "Astra"
}