@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ 
    "make" : "Toyota",
    "model" : "Yaris",
    "year": 2026
    
}

###

@newCar = {{postACar.response.body._id}}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6abcc5181bd63b4ab13675dc HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6abcd186c4fbd70f78f64025 HTTP/3.0
content-type: application/json

{ 
    "year" : 2022
}

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah